name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies with uv
      run: |
        uv sync
        uv pip install pytest pytest-cov
        uv add .[zoology] --no-build-isolation
    - name: Run tests
      run: |
        pytest tests/ -v 