name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install dependencies with uv
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install setuptools wheel
        uv sync --no-install-package zoology --no-install-package causal-conv1d --no-install-package mamba-ssm
        uv sync
    - name: Run tests
      run: |
        uv run pytest tests/ -v 